export const owner = {
  id: 3,
  remoteOwnerId: null,
  username: "yummy",
  email: "yululu0313@gmail.com",
  password: null,
  phoneNumber: "9138083520",
  createTime: "2019-05-22T02:23:00Z",
  name: "Kevin",
  vip: false,
  vipExpDate: null,
  restaurantInfos: [
    {
      id: 3,
      remoteRestaurantInfoId: null,
      name: "Yummy Chinese",
      faxNumber: "9135583082",
      phoneNumber: "5138848637",
      address: "15005 Metcalf Ave",
      city: "Overland Park",
      state: "KS",
      zip: "66223",
      webUrl: "https://etapthru.com/jos_overland_park",
      logoUrl: "https://etapthru.com/img/restaurants/3/logo.png",
      bannerUrl: "https://etapthru.com/img/restaurants/3/banner.png",
      encodedLogo: null,
      encodedBanner: null,
      keyword: "Asian, Cantonese, Chinese, Szechuan, Thai",
      latitude: 38.856262,
      longitude: -94.66727,
      taxRate: 0.08,
      ownerId: 3,
      minDelivery: 50,
      distance: null,
      restaurantInfoOrderTypes: [
        {
          id: 23,
          orderType: {
            id: 3,
            name: "Dine In",
            value: "DINE_IN",
          },
          startTime: null,
          endTime: null,
          minReadyMinutes: null,
          maxReadyMinutes: null,
          available: true,
          restaurantInfoOrderTypeSpecialTimes: [],
          orderCount: 0,
          currentDateTime: "2022-10-13T20:08:05.945592",
          currentRestaurantInfoOrderTypeSpecialTime: {
            id: null,
            startTime: null,
            endTime: null,
            minReadyMinutes: null,
            maxReadyMinutes: null,
            day: 4,
          },
        },
        {
          id: 24,
          orderType: {
            id: 4,
            name: "Pick Up",
            value: "PICK_UP",
          },
          startTime: null,
          endTime: null,
          minReadyMinutes: 0,
          maxReadyMinutes: 55,
          available: true,
          restaurantInfoOrderTypeSpecialTimes: [
            {
              id: 1,
              startTime: "15:00:00",
              endTime: "23:59:59",
              minReadyMinutes: 23,
              maxReadyMinutes: 27,
              day: 5,
            },
          ],
          orderCount: 0,
          currentDateTime: "2022-10-13T20:08:05.945645",
          currentRestaurantInfoOrderTypeSpecialTime: {
            id: null,
            startTime: null,
            endTime: null,
            minReadyMinutes: 0,
            maxReadyMinutes: 55,
            day: 4,
          },
        },
        {
          id: 140,
          orderType: {
            id: 5,
            name: "Delivery",
            value: "DELIVERY",
          },
          startTime: null,
          endTime: null,
          minReadyMinutes: 45,
          maxReadyMinutes: 60,
          available: true,
          restaurantInfoOrderTypeSpecialTimes: [],
          orderCount: 0,
          currentDateTime: "2022-10-13T20:08:05.945671",
          currentRestaurantInfoOrderTypeSpecialTime: {
            id: null,
            startTime: null,
            endTime: null,
            minReadyMinutes: 45,
            maxReadyMinutes: 60,
            day: 4,
          },
        },
        {
          id: 3270,
          orderType: {
            id: 2,
            name: "Walk In",
            value: "WALK_IN",
          },
          startTime: null,
          endTime: null,
          minReadyMinutes: null,
          maxReadyMinutes: null,
          available: true,
          restaurantInfoOrderTypeSpecialTimes: [],
          orderCount: 0,
          currentDateTime: "2022-10-13T20:08:05.945695",
          currentRestaurantInfoOrderTypeSpecialTime: {
            id: null,
            startTime: null,
            endTime: null,
            minReadyMinutes: null,
            maxReadyMinutes: null,
            day: 4,
          },
        },
        {
          id: 3856,
          orderType: {
            id: 6,
            name: "Buffet",
            value: "BUFFET",
          },
          startTime: null,
          endTime: null,
          minReadyMinutes: null,
          maxReadyMinutes: null,
          available: true,
          restaurantInfoOrderTypeSpecialTimes: [],
          orderCount: 0,
          currentDateTime: "2022-10-13T20:08:05.94572",
          currentRestaurantInfoOrderTypeSpecialTime: {
            id: null,
            startTime: null,
            endTime: null,
            minReadyMinutes: null,
            maxReadyMinutes: null,
            day: 4,
          },
        },
      ],
      paymentStatuses: [],
      restaurantInfoHours: [
        {
          id: 4703,
          day: 3,
          dayOfWeek: "WEDNESDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 4704,
          day: 5,
          dayOfWeek: "FRIDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 4705,
          day: 6,
          dayOfWeek: "SATURDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 5385,
          day: 4,
          dayOfWeek: "THURSDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 6870,
          day: 1,
          dayOfWeek: "MONDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 6948,
          day: 3,
          dayOfWeek: "WEDNESDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 8302,
          day: 1,
          dayOfWeek: "MONDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
        {
          id: 8442,
          day: 0,
          dayOfWeek: "SUNDAY",
          today: false,
          currentDate: null,
          startTime: "00:00:00",
          endTime: "23:59:59",
        },
      ],
      restaurantInfoStatuses: [
        {
          id: 5,
          facebook: false,
          google: false,
          appleMaps: false,
          appointmentTime: null,
          comment: null,
          googleRequestDate: null,
          googleFinishDate: "2020-07-08T20:24:48Z",
          googleWaitDays: 0,
          menuDone: true,
          salesName: "TapThru",
          autoPrint: true,
          appointmentDateTime: "2022-05-27T14:26:00Z",
          finishDateTime: "2021-10-31T13:00:00Z",
          setTime: false,
        },
      ],
      rewardRate: 0.05,
      fees: [
        {
          id: 1722,
          feeType: "TAP_THRU_DELIVERY",
          minDistance: 2.51,
          price: 6.99,
          maxDistance: 5,
        },
        {
          id: 1727,
          feeType: "TAP_THRU_DELIVERY",
          minDistance: 0,
          price: 6.88,
          maxDistance: 2.5,
        },
        {
          id: 1734,
          feeType: "DELIVERY",
          minDistance: 0,
          price: 4.99,
          maxDistance: 10,
        },
        {
          id: 1735,
          feeType: "DELIVERY",
          minDistance: 5.01,
          price: 6.99,
          maxDistance: 99,
        },
      ],
      ratings: [],
      averageRating: 0,
      deliveryFeeVisible: true,
      active: true,
      tapThru: true,
      tapThruDrive: false,
      tapThruDriveDoordash: false,
      remotePhoneOrdering: false,
      initialPosStatus: "MINIMIZED",
      receiveByFax: false,
      timeZone: "America/Chicago",
      applicationKey: null,
      ownDriver: true,
      receiveTip: true,
      announcement: "This is a test store!",
      voiceNotify: false,
      ipAddress: "136.33.178.14",
      localIpAddress: null,
      specialRequestAvailable: true,
      availableHours: [],
      images: null,
      tdrive: false,
      mRate: 1.2,
    },
  ],
  deviceToken: "ExponentPushToken[LyiOOFKhbmXJTE_QuwuSVd]",
  operatingSystem: "APPLE",
  smsNotify: false,
  emailNotify: true,
  securePassword: null,
  verifyCode: "358742",
  verified: true,
  verifyCodeExpDate: "2022-09-14T08:22:39Z",
  preferredLanguage: null,
  accessToken: null,
  tempPassword: null,
};
